package com.linkedin.backend.features.notifications.model;

public enum NotificationType {
    LIKE,
    COMMENT,
    GROUP_JOIN_REQUEST,
    GROUP_JOIN_ACCEPTED,
    RECRUITER_APPROVED,
    RECRUITER_REJECTED,
    RECRUITER_PERMANENTLY_REJECTED,
    JOB_REMOVED,
    POST_REMOVED,
    JOB_RECOMMENDATION,
    APPLICATION_STATUS,
    USER_BLOCKED,
    USER_UNBLOCKED
}
